### ISSUE TITLE
use Joda Money

### ISSUE THREAD

**Issue by minicuts** [fi-muni/PA165#6]

**Comment by mbriskar** [comment]
I think this would completely replace the Price entity and in order to persist it we would need to implement something like http://code.google.com/p/ddd-cqrs-base-project/source/browse/trunk/src/main/java/org/nthdimenzion/ddd/domain/sharedkernel/MoneyType.java . Is it worth making it more complicated for students?

**Comment by minicuts** [comment]
Ok not for now
